# Generated by Django 4.2.1 on 2023-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PEntry',
            fields=[
                ('part_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
