# Generated by Django 4.2.1 on 2023-06-04 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CEntry',
            fields=[
                ('cust_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60)),
                ('address', models.TextField(max_length=200, null=True)),
                ('contact', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
