# Generated by Django 4.2.1 on 2023-06-04 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cform', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DEntry',
            fields=[
                ('entry_id', models.IntegerField(primary_key=True, serialize=False)),
                ('parts', models.TextField(max_length=1000)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('time', models.DateTimeField()),
                ('cust_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cform.centry')),
            ],
        ),
    ]
